name: 过滤 IPV4 地址

on:
  schedule:
    - cron: '0 */6 * * *'  # 每隔6小时运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  filter-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 运行过滤脚本
      run: python script.py

    - name: 如果有更改则提交并推送
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add live_ipv4.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "更新 live_ipv4.txt" && git push)